/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/FormularioItem` | `/componentes/FormularioItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/ListaDeCompra` | `/componentes/ListaDeCompra`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/hooks/useItems` | `/componentes/hooks/useItems`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/tipos/item` | `/componentes/tipos/item`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/componentes/FormularioItem` | `/componentes/FormularioItem`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/componentes/ListaDeCompra` | `/componentes/ListaDeCompra`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/componentes/hooks/useItems` | `/componentes/hooks/useItems`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/componentes/tipos/item` | `/componentes/tipos/item`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/componentes/FormularioItem${`?${string}` | `#${string}` | ''}` | `/componentes/FormularioItem${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/componentes/ListaDeCompra${`?${string}` | `#${string}` | ''}` | `/componentes/ListaDeCompra${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/componentes/hooks/useItems${`?${string}` | `#${string}` | ''}` | `/componentes/hooks/useItems${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/componentes/tipos/item${`?${string}` | `#${string}` | ''}` | `/componentes/tipos/item${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/FormularioItem` | `/componentes/FormularioItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/ListaDeCompra` | `/componentes/ListaDeCompra`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/hooks/useItems` | `/componentes/hooks/useItems`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/componentes/tipos/item` | `/componentes/tipos/item`; params?: Router.UnknownInputParams; };
    }
  }
}
